version: '3.8'

services:
  web:
    image: odoo:17.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=SuperSecretPassword123!
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./custom_addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    restart: always

  db:
    image: postgres:16
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=SuperSecretPassword123!
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
